mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.urls import path, include  
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vumbora.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/vumbora/urls.py
from django.urls import path
from . import views

app_name = 'vumbora'
urlpatterns = [
    path('', views.index, name='index'),
    path('evento/<int:evento_id>/', views.details, name='details'),
    path('pesquisar_eventos/', views.pesquisar_eventos, name='pesquisar_eventos'),
    path('avaliacao/<int:evento_id>/', views.avaliacao, name='avaliacao'),
    path('lista_eventos_semana/', views.eventos_na_semana, name='lista_eventos_semana'),
    path('cadastrar_evento/', views.cadastrar_evento, name='cadastrar_evento'),
    path('logar/', views.logar, name='logar'),
    path('cadastrar_perfil/', views.cadastrar_perfil, name='cadastrar_perfil'),

]

mysite/vumbora/models.py
from django.db import models
from django.utils.timezone import now
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

# Create your models here.
class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, unique=True)
    tipo = models.CharField(max_length=1,default = 'F' ,choices=[
        ('F', 'Física'),
        ('J', 'Jurídica')
    ])
    identidade = models.CharField(max_length =14)
    foto = models.ImageField(upload_to='images/', null=True, blank=True)
    def __str__(self):
        return self.nome

class Bairro(models.Model):
    nome = models.CharField(max_length= 200)
    zona = models.CharField(max_length=2, choices=[
        ('ZN', 'Zona Norte'),
        ('ZS','Zona Sul'),
        ('ZL', 'Zona Leste'),
        ('ZO', 'Zona Oeste')
    ])
    def __str__(self):
        return self.nome

class Local(models.Model):
    verbose_name = "Locais" 
    nome = models.CharField(max_length=200)
    bairro = models.ForeignKey(Bairro,on_delete=models.CASCADE, null=True)
    cep = models.CharField(max_length=20)
    rua= models.CharField(max_length=200)
    numero = models.CharField(max_length=4, blank = True)
    estacionamento = models.BooleanField(default = True)
    class Meta:
        verbose_name_plural = "Locais"
    def __str__(self):
        return self.nome


class Genero(models.Model):
    genero = models.CharField(max_length=1,choices =[
        ('E', 'Exposição'),
        ('F', 'Festa'),
        ('G', 'Gastronomia'),
        ('S', 'Show'),
        ('T','Teatro'),  
    ])
    class Meta:
        verbose_name_plural = "Gêneros"
    def __str__(self):
        choices_dict = {
            'E': 'Exposição',
            'F': 'Festa',
            'G': 'Gastronomia',
            'S': 'Show',
            'T': 'Teatro',     
        }
        return choices_dict.get(self.genero, '')
    
class Evento(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.CharField(max_length=200, null=True)
    datahora = models.DateTimeField(default = now)
    valor = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True)
    arte = models.ImageField(upload_to='images/', null=True, blank = True)
    genero = models.ManyToManyField(Genero)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.nome

class Avaliacao(models.Model):
    nota = models.IntegerField(default=5,blank= True,validators=[MaxValueValidator(5), MinValueValidator(1)])
    comentario = models.CharField(max_length=200, null=True,blank=True)
    data = models.DateTimeField(default = now)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    evento = models.ForeignKey('Evento', on_delete=models.CASCADE, null=True)    

class Comenta(models.Model):
    comentario = models.CharField(max_length=200)
    data_hora = models.DateTimeField(default=now)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE,null=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE,null=True)
    class Meta:
        verbose_name_plural = "Comentários"

class Images(models.Model):
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name="evento_images", null = True)
    class Meta:
        verbose_name_plural = "Images"
# python -m pip install Pill

mysite/vumbora/forms.py
from django import forms
from .models import Evento, Usuario, Local
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Usuario,Avaliacao


class PesquisaEventoForm(forms.Form):
    termo_pesquisa = forms.CharField(label=' Eveno', max_length=100)


class AvaliacaoForm(forms.ModelForm):
    class Meta:
        model = Avaliacao
        fields = ['nota', 'comentario', 'usuario'] # campos que serão exibidos no formulário
        widgets = {
            'comentario': forms.Textarea(attrs={'class': 'form-comentario', 'placeholder': 'Comentário', 'id': 'id_comentario'}),
        }

class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)
    
class UsuarioForm(UserCreationForm):
    tipo = forms.ChoiceField(choices=[
        ('F', 'Física'),
        ('J', 'Jurídica')
    ])
    identidade = forms.CharField(max_length=14)
    foto = forms.ImageField(required=False)
    nome = forms.CharField(max_length=200)
    class Meta:
        model=User
        fields = ['username','email','password1','password2','nome', 'tipo', 'identidade', 'foto']

class EventoCadastro(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['nome', 'descricao', 'datahora', 'valor', 'local', 'arte', 'genero',]
        widgets = {
            'datahora': forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        labels = {
            'datahora': 'Data e Hora do Evento',
            'descricao': 'Descrição',
            'genero': 'Gênero do Evento'
        }
  

mysite/vumbora/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django import forms
from .models import Evento, Usuario,Avaliacao
from .forms import AvaliacaoForm, UsuarioForm, UserCreationForm, EventoCadastro, LoginForm
from datetime import datetime, timedelta
from django.http import HttpResponseRedirect
from django.urls import reverse
from .services import CadastrarPerfilService, LogarService, CadastrarEventoService
from django.views import View
from django.urls import reverse

### View INDEX
############
def index (request):
    evento_list = Evento.objects.order_by('datahora')[:5]
    context = {
        'evento_list': evento_list
    }
    return render(request,'vumbora/index.html',context)


### View DETAIL
############
def details(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    context = {
        'evento': evento,
        'arte_url': evento.arte.url if evento.arte else None,
        'event' : Evento.objects.get(pk=evento.pk),
    }
    return render(request, 'vumbora/detail.html', context)

class PesquisaEventoForm(forms.Form):
    termo_pesquisa = forms.CharField(label='Pesquisar Evento', max_length=100)

### View PESQUISAR Eventos
#############
def pesquisar_eventos(request):
    eventos = Evento.objects.all()
    form = PesquisaEventoForm()
    
    if request.method == 'POST':
        form = PesquisaEventoForm(request.POST)
        if form.is_valid():
            termo_pesquisa = form.cleaned_data.get('termo_pesquisa', '')
            eventos = Evento.objects.filter(nome__icontains=termo_pesquisa)
    
    return render(request, 'vumbora/resultado_pesquisa.html', {'form': form, 'eventos': eventos})

       
### View AVALIAÇÃO
##############
def avaliacao(request, evento_id):
    evento = Evento.objects.get(pk=evento_id)
    avaliacoes = Avaliacao.objects.filter(evento_id=evento_id)

    if request.method == 'GET':
        form = AvaliacaoForm()
        return render(request, 'vumbora/avaliacao.html', {'evento': evento, 'avaliacoes': avaliacoes, 'form': form})
    elif request.method == 'POST':
        print(request.POST)
        form = AvaliacaoForm(request.POST)
        if form.is_valid():
            nova_avaliacao = form.save(commit=False)
            # avaliacao.usuario = request.user
            nova_avaliacao.evento = evento
            nova_avaliacao.save()
            # return JsonResponse({'success': True})
            return HttpResponseRedirect(reverse('vumbora:avaliacao', args=(evento.id,)))
        else:
            return render(request, 'vumbora/avaliacao.html', {'evento': evento, 'avaliacoes': avaliacoes, 'form': form})
            

### View EVENTOS na semana
##############
def eventos_na_semana(request):
     # Lógica para filtrar eventos da semana, se aplicável
    hoje = datetime.now()
    inicio_semana = hoje - timedelta(days=hoje.weekday())
    fim_semana = inicio_semana + timedelta(days=6)
    eventos_semana = Evento.objects.filter(datahora__range=[inicio_semana, fim_semana])

    # Adicione uma mensagem se não houver eventos
    mensagem_sem_eventos = "Não há eventos a serem realizados nesta semana." if not eventos_semana else None

    # Renderiza o template com os eventos
    return render(request, 'vumbora/lista_eventos_semana.html', {'eventos_semana': eventos_semana, 'mensagem_sem_eventos': mensagem_sem_eventos})

### View Login
####################

def logar(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'vumbora/login.html', { 'form': form})
    elif request.method == 'POST':
        ls = LogarService()
        if ls.Logar(request):
            return redirect(reverse('vumbora:index'))
        else: 
            form = LoginForm()
            return render(request,'vumbora/login.html',{'form': form})
            
### View Cadastrar Perfil
###################        
    
def cadastrar_perfil(request):
    if request.method == 'GET':
        form = UsuarioForm()
        return render(request, 'vumbora/cadastro_perfil.html', { 'form': form})
    if request.method == 'POST':
        cps = CadastrarPerfilService()
        if cps.cadastrar_perfil(request):
            return redirect(reverse('vumbora:index'))
        else:
            form = UsuarioForm(request.POST)
            return render(request, 'vumbora/cadastro_perfil.html', {'form': form}) 


### View Cadastrar Evento
###################
             
def cadastrar_evento(request):
    if request.method == 'POST':
        service = CadastrarEventoService()
        deu_certo = service.cadastrar_evento(request)
        if deu_certo:
            return redirect('vumbora:index')
    else:
        form = EventoCadastro()
    return render(request, 'vumbora/cadastrar_evento.html', {'form': form})

mysite/vumbora/templates/vumbora/cadastrar_evento.html
<!DOCTYPE html>

{% load static %}

{% include 'vumbora/header.html' %}

<link rel="stylesheet" href="{% static 'css/cadastrar_evento.css' %}">

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastro de Evento</title>
</head>
<body>

  <h2>Cadastro de Evento</h2>
  <form method="post" action="{% url 'vumbora:cadastrar_evento' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Cadastrar Evento</button>
  </form>

  <hr>

</body>
</html>

mysite/vumbora/templates/vumbora/cadastro_perfil.html
{% load static %}

{% include 'vumbora/header.html' %}
    
<link rel="stylesheet" href="{% static 'css/cadastro_perfil.css' %}">

<form method="POST" novalidate>
	{% csrf_token %}
	<h2>Cadastrar Perfil</h2>
	{% for field in form %}
	<p id="formulario_cadastro">
		{% if field.errors %}
		<ul class="errorlist">
			{% for error in field.errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
	 	{{ field.label_tag }}<br>
		{{ field }}
	</p>
	{% endfor %}
	<br>
	<div id="botao_cadastrar">	
	<input  type="submit" value="Cadastrar Perfil" />
	</div>
</form>

mysite/vumbora/templates/vumbora/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>{{ evento.nome}}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'vumbora/css/detail.css' %}"/>
  <script src="/mysite/static/vumbora/js/detail.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>

<body>
{% include 'vumbora/header.html' %}

<h1 id="nome-evento">
    {{ evento.nome }}
</h1>
{% load static%}
<!-- <div id="imagem-evento">  
    <a id= "prevButton" class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a id="nextButton" class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
        {% for image in event.evento_images.all %}
            <div class="carousel-item{% if forloop.first %} active {% endif %}">
                <img src="{{ image.image.url }}" id= "imgcarosel" class="d-block w-100 img-fluid" alt="{{ image.nome }}" style="height: 450px; width: 90%;">
        {% endfor %}
            </div>
        </div>
    </div>
</div> -->
 
<div id="quesitos-evento" class="container" style="display:flex;">
    <button type="button" class="btn btn-primary rounded-pill" id="descricao-evento"><a href="{% url 'vumbora:details' evento.id %}" style="text-decoration: none; color: black;"><strong> Descrição </strong></a> </button> 
        
    <button type="button" class="btn btn-primary rounded-pill" id="avaliacao-evento"><a href="{% url 'vumbora:avaliacao' evento.id %}" style="text-decoration: none; color: black;"> <strong> Avaliação </strong></a> </button> 

    <button type="button" class="btn btn-primary rounded-pill" id="perguntas-evento"> <strong> Perguntas </strong> </button> 
</div>

<div id="todas-informaçoes">
    <div id = "detalhes" class="info">
        <p id="nome-central">
            <h2>{{ evento.nome }}</h2>
        </p>
        <p>
            <strong>Data:</strong> {{ evento.datahora|date }}
        </p>
        <p>
            <strong>Horário:</strong> {{ evento.datahora|time }}
        </p>
        <p>
            <strong>Local:</strong> {{ evento.local }}
        </p>
        <p>
            <strong>Descrição:</strong> {{ evento.descricao }}
        </p>
    </div>
    <div id="extras">
        <div id="arte-evento">
            {% if arte_url %}
                <img src="{{ arte_url }}" >
            {% else %}
                <img src="/media/images/images/imagedefault/defaultevento.png">
            {% endif %}
        </div>
        
        <div id="informacoes-adicionais-evento">
            <strong>Informações adicionais</strong>
            <strong>Preço:</strong> R${{ evento.valor }}
            <strong>Estacionamento: </strong> 
            {% if evento.local.estacionamento %}
                Sim
            {% else %}
                Não
            {% endif %}
        </div>
    </div>
</div>
<div id="evento-local">
    <button type="button" class="btn btn-primary rounded-pill" id="local-evento"> <strong> Local </strong> </button> 
    INFORMAÇÕES A SEREM ADICIONADAS
</div>
<div id="producao">
    <button type="button" class="btn btn-primary rounded-pill" id="producao-botao"> <strong> Produção </strong> </button> 
</div>
</body>

mysite/vumbora/templates/vumbora/footer.html
<footer>
    
</footer>

mysite/vumbora/templates/vumbora/header.html
{% load static %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'vumbora/css/header.css' %}">
</head>
<header>
    <div id="barra" class = "container" style="display: flex;" >
        <a href="{% url 'vumbora:index' %}" style="text-decoration: none;"><h1 style="font-family: Asteristico;"> VUMBORA? </h1></a>
        <div id="pesquisa-barra-de-navegacao">
            
            <form id="form" action="{% url 'vumbora:pesquisar_eventos' %}" method="post">
                {% csrf_token %}
                <div id="procura">
                <input  name = 'termo_pesquisa' type="text" class="form-control rounded-pill" placeholder="Busque eventos..." id="pesquisa">
                <button type="submit" class="btn btn-primary rounded-pill" style="width: fit-content;" id="icone-pesquisa"><i class="fas fa-search"></i></button>
                </div>
            </form>
        </div>
        <div id="filtro-localizacao-barra">
            <button class="btn btn-primary rounded-pill" style="width: fit-content; id="botao-loc">Localização</button>
        </div>
        <div id="barra-evento">
            <a href="{% url 'vumbora:cadastrar_evento' %}" id="icone-evento"></a>
            <div id="meus-eventos-barra">
                <a href="{% url 'vumbora:cadastrar_evento' %}" style="text-decoration: none; color:red "> Meus Eventos</a>
            </div>
        </div>
        <div id="usuario-barra">
            <a href="{% url 'vumbora:cadastrar_perfil' %}" id="icone-perfil"></a>
            <div id="login-barra">
                {% if user.is_authenticated %}
                <a href="{% url 'vumbora:logar' %}" style="text-decoration: none; color: red;">
                    {{ user.username }}</a>
                {% else %}
                <a href="{% url 'vumbora:logar' %}" style="text-decoration: none; color: red;   ">Login</a>
                {% endif %}
            </div>
        </div>
        <div id="opcoes-barra">
            <button href="#" id="icone-barra"></button>
        </div>
    </div>
</header>

mysite/vumbora/templates/vumbora/index.html
{% load static %}

{% include 'vumbora/header.html' %}
    
<link rel="stylesheet" href="{% static 'css/index.css' %}">

{% if evento_list %}

    <h1>Eventos cadastrados</h1>
    <ul>
        {% for evento in evento_list %}
            <li><a href="{% url 'vumbora:details' evento.id %}">{{ evento.nome }}</a></li>
        {% endfor %}

        <a href="{% url 'vumbora:lista_eventos_semana' %}"> Listar Eventos da Semana </a>
    </ul>
{% else %}
    <p>Não há eventos cadastrados.</p>
{% endif %}
{% if user.is_authenticated %}
    | Logado como: {{ user.username }}
{% endif %}


<!--/vumbora/<int:evento_id>/-->

mysite/vumbora/templates/vumbora/lista_eventos_semana.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vumbora/css/eventos_semana.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,700&display=swap" rel="stylesheet">
    <title>Eventos Semana</title>
</head>
<body>
    
    <div>
        {% include 'vumbora/header.html' %}
    </div>
    
    <div class="filtragem">

        <form class="campolistagem" method="get" action="{% url 'vumbora:lista_eventos_semana' %}">
            <div class = "filtros-pesquisa">
                <label for="tipo_evento"></label>
            <select id="tipo">
                <option value="1">Tipo</option>
                <option value="2">Option 2</option>
                <option value="3">Option 3</option>
                <option value="4">Option 4</option>
            </select>
            
            <label for="zona_evento"></label>
            <select id="tipo">
                <option value="1">Zona</option>
                <option value="2">Option 2</option>
                <option value="3">Option 3</option>
                <option value="4">Option 4</option>
            </select>
            
            <label for="valor_evento"></label>
            <select id="tipo">
                <option value="1">Valor</option>
                <option value="2">Option 2</option>
                <option value="3">Option 3</option>
                <option value="4">Option 4</option>
            </select>

            <label for="data_evento"></label>
            <select name="filtro_semana" id="filtro_semana">
                <option>Data</option>
                <option value="evento_list" >Todos os Eventos</option>
                <option value="eventos_semana">Eventos da Semana</option>
            </select>
            <input class="button-filtro" type="submit" value="Buscar">    
            </div>
        </form>
    </div>    
    <div class = "resultado-filtragem">   
        {% if eventos_semana and request.GET.filtro_semana == 'eventos_semana' %}
            <h2 class="msgbusca"> Eventos da semana </h2>
            <div class="lista-eventos-pai">
                {% for evento in eventos_semana %}
                <div class="all">
                    <div class="card">
                        {% if evento.arte%}
                        <div class="img">
                            <img src="{{evento.arte.url}}">
                        </div>
                        {%else%}
                        <div class="img">
                            <img src="https://v0.betalabs.cloud/ecommerce/lifebike/img/unavailable.jpg">
                        </div>
                        {%endif%}
                        <div class="content">
                            <p class="data">{{evento.datahora|date:"M"}} <br><strong>{{evento.datahora.day}}</strong></p>
                            <p class="titulo">{{evento.nome}}</p>
                        </div>
                        <p class="descricao">{% if evento.descricao|length > 30 %} {{ evento.descricao|slice:":30" }}...{% else %}{{ evento.descricao }}{% endif %}</p>
                        <div class ="informacoes">
                            <p class="local-horario">{{evento.local}} - {{evento.datahora.hour}}:{{evento.datahora.minute|stringformat:"02d"}}</p>
                            <p class="ingresso" > 
                                {% if evento.valor == 0 %} Evento gratuito 
                                {% else %} Ingressos a partir de R${{evento.valor}} Reais 
                                {% endif %}</p>
                        </div>
                        <a href="{% url 'vumbora:details' evento.id %}"  rel="noopener noreferrer" class="ver-mais">Ver Mais</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
        <h2 class="msgbusca"> {{ mensagem_sem_eventos }} </h2>
        {% endif %}
    </div>
</body>
</html>

mysite/vumbora/templates/vumbora/login.html
{% load static %}

{% include 'vumbora/header.html' %}

<form method="POST" novalidate>
	{% csrf_token %}
	<h2>Login</h2>
	{{form.as_p}}
	<input type="submit" value="Login" />
</form>

mysite/vumbora/templates/vumbora/resultado_pesquisa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vumbora/css/resultado_pesquisa.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,700&display=swap" rel="stylesheet">
    <title>Resultados da sua pesquisa</title>
</head>

<body>
    {% include 'vumbora/header.html' %}
    <p class="pag-titulo">
    <h1>Resultados da Pesquisa</h1>
    </p> 

    {% if eventos %}
    {% for evento in eventos %}
    <div class="all">
        <div class="card">
            {% if evento.arte%}
            <div class="img">
                <img src="{{evento.arte.url}}">
            </div>
            {%else%}
            <div class="img">
                <img src="https://v0.betalabs.cloud/ecommerce/lifebike/img/unavailable.jpg">
            </div>
            {%endif%}
            <div class="content">
                <p class="data">{{evento.datahora|date:"M"}} <br><strong>{{evento.datahora.day}}</strong></p>
                <p class="titulo">{{evento.nome}}</p>
            </div>
            <p class="descricao">
                {% if evento.descricao|length > 30 %} 
                {{ evento.descricao|slice:":30" }}...{% else %}
                {{evento.descricao}}
                {% endif %}</p>
            <div class="informacoes">
                <p class="local-horario">{{evento.local}} -
                    {{evento.datahora.hour}}:{{evento.datahora.minute|stringformat:"02d"}}</p>
                <p class="ingresso">
                    {% if evento.valor == 0 %} Evento gratuito
                    {% else %} Ingressos a partir de R${{evento.valor}} Reais
                    {% endif %}</p>
            </div>
            <a href="{% url 'vumbora:details' evento.id %}" rel="noopener noreferrer" class="ver-mais">Ver Mais</a>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p class="pag-titulo">
    <h2>Nenhum evento encontrado</h2>
    </p>
    {% endif %}
</body>

</html>